name: Prefect Recursive Register
author: Aldwyn Cabarrubias
description: Enable the auto-registration of Prefect flows recursively. Limited to Kubernetes (EKS) run config and Docker (ECR) storage for now.
branding:
  icon: cloud-lightning
  color: blue

inputs:
  prefect-project-name:
    description: Prefect project name
    required: true
  create-prefect-project:
    description: Whether to create project if it does not exist
    default: "false"
    required: true
  project-description:
    description: A description of the project to be used when creating it
    required: false
  docker-registry-url:
    description: Docker registry URL
    required: true
  flows-root-directory:
    description: The root directory of the Python scripts that have Flow contexts. Default is "."
    required: true
    default: "."
  dockerfile-path:
    description: Path of the Dockerfile. Default is Dockerfile
    required: true
    default: Dockerfile
  # k8s-job-template-path:
  #   description: Kubernetes Job template path
  #   required: false
  # enable-dask-executor:
  #   description: Whether to enable DaskExecutor
  #   required: false
  #   default: "false"

runs:
  using: composite
  steps:
    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Build base Docker image
      shell: bash
      run: docker build -t prefect-base -f ${{ inputs.dockerfile-path }} .

    - name: Dockerize and register Prefect flows
      shell: bash
      run: |
        docker_workdir=$(docker image inspect prefect-base | jq -r '.[].Config.WorkingDir')
        flows_root_dir=${docker_workdir%%*(/)}${{ inputs.flows-root-directory }}

        docker run --rm \
          -v "${{ github.action_path }}:/tmp/prefect-action/" \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /home/runner/.docker/:/root/.docker/ \
          -e PREFECT__CLOUD__API_KEY=$PREFECT__CLOUD__API_KEY \
          prefect-base python3 /tmp/prefect-action/index.py \
            --project ${{ inputs.prefect-project-name }} \
            --create-project ${{ inputs.create-prefect-project }} \
            --path $flows_root_dir \
            --docker-registry-url ${{ inputs.docker-registry-url }}
