name: Prefect Recursive Register
author: Aldwyn Cabarrubias
description: Enable the auto-registration of Prefect flows recursively. Limited to Kubernetes (EKS) run config and Docker (ECR) storage for now.
branding:
  icon: cloud-lightning
  color: blue

inputs:
  prefect-project-name:
    description: Prefect project name
    required: true
  create-prefect-project:
    description: Whether to create project if it does not exist
    default: "false"
    required: true
  project-description:
    description: A description of the project to be used when creating it
    required: false
  base-docker-image:
    description: The base Docker image of Prefect to be used. Can be a local or remote Docker image.
    required: true
  docker-registry-url:
    description: Docker registry URL
    required: true
  flows-root-directory:
    description: The root directory of the Python scripts that have Flow contexts. Default is "."
    required: true
    default: "."
  # mock-prefect-secrets:
  #   description: YAML key-value dictionary in string format. Use it with a pipe symbol "|" to set a multiline value
  #   required: true
  #   default: '{}'
  # k8s-job-template-path:
  #   description: Kubernetes Job template path
  #   required: false
  # enable-dask-executor:
  #   description: Whether to enable DaskExecutor
  #   required: false
  #   default: "false"

runs:
  using: composite
  steps:
    - name: Dockerize and register Prefect flows
      shell: bash
      run: |
        docker_workdir=$(docker image inspect prefect-base | jq -r '.[].Config.WorkingDir')
        flows_root_dir=${docker_workdir%%*(/)}/${{ inputs.flows-root-directory }}
        is_create_project=$([[ "${{ inputs.create-prefect-project }}" == "true" ]] && echo --create-project || echo)

        docker run --rm \
          -v "${{ github.action_path }}:/tmp/prefect-action/" \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /home/runner/.docker/:/root/.docker/ \
          -e PREFECT__CLOUD__API_KEY=$PREFECT__CLOUD__API_KEY \
          -e PREFECT__CLOUD__USE_LOCAL_SECRETS=false \
          prefect-base python3 /tmp/prefect-action/index.py \
            $is_create_project \
            --schedule \
            --project ${{ inputs.prefect-project-name }} \
            --path $flows_root_dir \
            --docker-registry-url ${{ inputs.docker-registry-url }}
            # --mock-secrets "$mock_secrets_json"
